### ISSUE TITLE
Support copy down of Select field values

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.bugp#51]
If a select field like Grant Status is added to a profile used for batch update, the copy down function to replicate the value in the field from the first row into all lower rows seems to fail silently.

**Comment by pradpnayak** [comment]
Hi Joe,

I just tried on our testing server (http://mrg.jmaconsulting.biz). The lower rows seems to copy first row without any error when clicked on copy icon.

**Comment by pradpnayak** [comment]
Closing this as it was issue with other extension.
